name: Bug
description: Report a bug
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: urgent
    attributes:
      label: Is this urgent?
      description: |
        Is this a critical bug, or do you need this fixed urgently?
      options:
        - "No"
        - "Yes"
  - type: dropdown
    id: affected-parts
    attributes:
      label: What parts are affected
      description: |
        Is this related to the app or server?
      options:
        - "Frontend"
        - "Backend"
        - "Both"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What are the Server/Client versions of KitchenOwl
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: "What's the problem 🤔"
      placeholder: "That feature does not work..."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Share your logs
      description: If you have any relevant logs you can share them here.
      render: log
  - type: textarea
    id: config
    attributes:
      label: Share your configuration
      description: Share your configuration such as `docker-compose.yml`. Ensure to remove URLs/IPs.
      render: yml

